### ISSUE TITLE
No such file or directory when trying to run /node_modules/node-switchmate/bin

### ISSUE THREAD

**Issue by jeffl78** [emmcc/node-switchmate#11]
I imagine I don’t have one of the extras for a prerequisite installed or performed correctly.  I’m using the iOS raspberry pi app and a raspberry pi3b.  I ordered the recommended Bluetooth adapter but it rn it appears I don’t have some file installed correctly.  If anyone can help it would be appreciated as I just got a few of these switches.

pi@raspberrypi:~ $ sudo su
root@raspberrypi:/home/pi# /node_modules/node-switchmate/bin
bash: /node_modules/node-switchmate/bin: No such file or directory
root@raspberrypi:/home/pi#

**Comment by jeffl78** [comment]
I’m running js node version 7.9.0 because something I’m running crashes if I change it if I’m remembering correctly.  I’ve only had a pi a few months playing around but have a homebridge with about 7 active plugins @ 30 or so devices, a wink 1, & SmartThings vs 2 hub, so know a little about the subject.

**Comment by throw-pi-at-your-face** [comment]
My node-switchmate folder was in /usr/local/lib/node_modules, but I don't know if that was just me or if that was weirdness from my installation. I don't know much about it, so I'm probably not much help. I will say that if you have the capability to, it makes it a lot easier to use it with a monitor and mouse as well (at least for me for this part) because then you can navigate from there directly to the /usr/local/lib//node_modules/node-switchmate/ and right-click the bin folder and select open in Terminal, but that's just me and all the typos that have made me have to re-write commands a thousand times. :) And not having success when I tried just typing it out that way. Anyway, I may be explaining something that I actually know less about than you, sorry if I am. :)

The way I have to type it as follows, but again, I don't know if I installed this right or if mine is in the "right" spot.

cd /usr/local/lib/node_modules/node-switchmate/bin

After that, sudo su and get on with ./discover.switchmate, etc, etc.

**Comment by jeffl78** [comment]
I had it running for a while but reinstalled everything so to a separate issue.  Then, I got the Bluetooth fob recommended for pi3b & now all I get is this and have tried many fixes with no luck:

ERROR LOADING PLUGIN homebridge-switchmate:
[2018-2-17 00:08:45] Error: Cannot find module 'bluetooth-hci-socket'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-switchmate/node_modules/noble/lib/hci-socket/hci.js:6:26)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

**Comment by jeffl78** [comment]
Wait sorry, I got that figured out too but now it won’t discover my switches.

**Comment by jeffl78** [comment]
I can get pi to give me an id for each of my devices when I try to get pi to add a switchmate device using the id pi fails to find anything after about 5 minutes.  I may open a new issue since this is getting buired.  I bought this switchmates specifically for this project because I rent and it seemed to make sense.  If anyone can help I would appreciate it immensely, as I think  I’m going to pull start my hair out soon, lol.  I have read the Bluetooth fob my be the issue & the original raspi3b setup is the way to go after an update.  I should mention I didn’t do any configuration of noble device, just installed and the might be incorrect.  Come to think of it I didn’t configure anything I installed for the project beyond instruction except homebridge.  Hope some of this info helpes give a feel for where I’m at with this.  Please ask me anything if you think it may help.

**Comment by jeffl78** [comment]
I’m currently running the Bluetooth USB fob recommended in the instructions.  To my knowledge I have followed the procedure as discribeded and set up the minimum requirement as I didn’t want change any settings from default to help diagnose the problem I’m having.

**Comment by jeffl78** [comment]
I’ll close this issue after a while if no one responds so I want to thank you throw-pi-at-your-face.  I have opened a separate issue that is specific to the pi failing to add device after entering id

**Comment by kianrafiee** [comment]
my node-switchmate folder is also not in the modules folder in node folder, its in /usr/bin/node-switchmate
