### ISSUE TITLE
./discover.switchmate error

### ISSUE THREAD

**Issue by beefycheddar** [emmcc/node-switchmate#20]
I just went through the homebridge and node-switchmate install process on OSX 10.13.6. When I run discover.switchmate, it returns the error below. What have I missed? Any guidance is appreciated. 

`mini1:bin brett$ sudo ./discover.switchmate 
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'xpc-connection'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-switchmate/node_modules/noble/lib/mac/highsierra.js:7:21)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
mini1:bin brett$ `

output of "echo $PATH" /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands

the /etc/paths file contains:

/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin

**Comment by bwalls** [comment]
Me, too! Although on a Raspberry Pi.

**Comment by jacobwhite** [comment]
Any fix for this?
