### ISSUE TITLE
Error while pairing

### ISSUE THREAD

**Issue by AlexLamprianidis** [emmcc/node-switchmate#6]
Hey i am getting the following error when pairing my switchmate

`Locating d14d6d58c414.
/usr/local/lib/node_modules/node-switchmate/bin/pair.switchmate:50
    PairMode.PairSwitchmate();
             ^

TypeError: PairMode.PairSwitchmate is not a function
    at onFound (/usr/local/lib/node_modules/node-switchmate/bin/pair.switchmate:50:14)
    at EventEmitter.onDiscoverWithFilter (/usr/local/lib/node_modules/node-switchmate/node_modules/noble-device/lib/util.js:97:11)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at Noble.constructor.onDiscover (/usr/local/lib/node_modules/node-switchmate/node_modules/noble-device/lib/util.js:30:29)
    at emitOne (events.js:77:13)
    at Noble.emit (events.js:169:7)
    at Noble.onDiscover (/usr/local/lib/node_modules/node-switchmate/node_modules/noble-device/node_modules/noble/lib/noble.js:137:10)
    at emitMany (events.js:108:13)
    at emit (events.js:182:7)
`

**Comment by AMoo-Miki** [comment]
Are you still having this problem? What version of "noble-device" do you have in your node_modules?

**Comment by Brandenbass** [comment]
I am new to linux completely and have the same exact error as stated above, but I don't know how to confirm what version of noble-device I have.

EDIT:  I have located it.  I have 1.4.1 if that helps.
